install_dependency:
	# You may need to run this as a 'sudo ...' command
	# You may need to run this as a 'sudo ...' command
	# You may need to run this as a 'sudo ...' command
	cd ../ && make install && cd -

uninstall_dependency:
	# You may need to run this as a 'sudo ...' command
	# You may need to run this as a 'sudo ...' command
	# You may need to run this as a 'sudo ...' command
	cd ../ && make uninstall && cd -
