install_dependency:
	# You may need to run this as a 'sudo ...' command
	# You may need to run this as a 'sudo ...' command
	# You may need to run this as a 'sudo ...' command
	cd ../tsdb_abstraction_layer && make install && cd -

uninstall_dependency:
	# You may need to run this as a 'sudo ...' command
	# You may need to run this as a 'sudo ...' command
	# You may need to run this as a 'sudo ...' command
	cd ../tsdb_abstraction_layer && make uninstall && cd -
