version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: "Install pytest and supporting packages"
          command: |
            pyenv global 3.9.0  # Pins the Python version. Needed because host
                                # has multiple Python 3 versions installed.
                                # Without version pinning, python3 invocation
                                # below fails.
            pip install --upgrade pip  # to ensure we're latest version of pip.
            pip install -U pytest  # required to run pytest below
            pip install coverage # For code coverage
            pip install requests # required for HTTP querying
            pip install -U pip setuptools # reqd to install argus_tal package
            pip install jsonschema
            pip install wheel
      - run:
          name: "Run TSDB Abstraction Layer (TAL) tests and code coverage"
          command: |
            cd tsdb_abstraction_layer
            make init
            make code_coverage   # Runs tests & generates code coverage data.
            coverage html --directory=/tmp/htmlcov1  # Generate an html report.
      - run:
          name: "Run Quilt tests and code coverage"
          command: |
            cd tsdb_abstraction_layer
            make install   # install argus_tal package
            cd ../quilt
            make code_coverage # Run tests and code coverage for Quilt code
            coverage html --directory=/tmp/htmlcov2  # Generate an html report.
      - store_artifacts:
            # Copies the html report from /tmp/htmlcov1 to artefacts.
            # To access: Via argustal_coverage/index.html under the "ARTIFACTS" tab.
            path: /tmp/htmlcov1
            destination: argustal_coverage
      - store_artifacts:
            # Copies the html report from /tmp/htmlcov2 to artefacts.
            # To access: Via mc_analytics_coverage/index.html under the "ARTIFACTS" tab.
            path: /tmp/htmlcov2
            destination: mc_analytics_coverage
