version: 2.1
jobs:
  build:
    machine:
      # image: ubuntu-1604:201903-01
      image: ubuntu-2004:202010-01
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: "Install pytest and supporting packages"
          command: |
            pyenv global 3.7.0  # Pins the Python version. Needed because host
                                # has multiple Python 3 versions installed.
                                # Without version pinning, python3 invocation
                                # below fails.
            pip install --upgrade pip  # to ensure we're latest version of pip.
            pip install -U pytest  # required to run pytest below
            pip install coverage # For code coverage
            pip install requests # required for HTTP querying
            pip install -U pip setuptools # reqd to install argus_tal package
      - run:
          name: "Run TSDB Abstraction Layer (TAL) tests and code coverage"
          command: |
            cd tsdb_abstraction_layer
            make code_coverage   # Runs tests & generates code coverage data.
            coverage html --directory=/tmp/htmlcov  # Generate an html report.
      - store_artifacts:
            # Copies the html report from /tmp/htmlcov to the artefacts location
            # which can be accessed via a browser on the CircleCI dashboard.
            path: /tmp/htmlcov
            destination: htmlcov
      - run:
          name: "Machine analytics tests"
          command: |
            cd tsdb_abstraction_layer
            make install   # install argus_tal package
            cd ../machine_analytics
            make test   # Basic protection for machine analysis code
